### ISSUE TITLE
aws model

### ISSUE THREAD

**Issue by Di-Gu** [TRI-ML/permatrack#1]
Thx for releasing the model. Just a quick question, since I'm new to AWS. How to get the model from AWS s3:bucket, the [Link](https://s3.console.aws.amazon.com/s3/object/tri-ml-public?region=us-east-1&prefix=github/permatrack/nu_stage_3_17fr.pth) seems cannot be downloaded from the AWS webpage.

**Comment by pvtokmakov** [comment]
Hi,

sorry about that, I've updated the links, the models should be directly downloadable now.

**Comment by Di-Gu** [comment]
cool
