### ISSUE TITLE
Reproduce results on KITTI test

### ISSUE THREAD

**Issue by noahcao** [TRI-ML/permatrack#16]
Hi,

Could you provide the pretrained model to reproduce the tracking results on KITTI test? I found the [pretrained weights](https://tri-ml-public.s3.amazonaws.com/github/permatrack/kitti_half_pd_5ep.pth) which is for tracking on KITTI validation only.

**Comment by pvtokmakov** [comment]
Hi,

thanks for your interest in our work! The model trained on the full training set of KITTI is available under this link: https://tri-ml-public.s3.amazonaws.com/github/permatrack/kitti_full.pth
