### ISSUE TITLE
PD dataset

### ISSUE THREAD

**Issue by RaymondByc** [TRI-ML/permatrack#3]
I can not find a valid email address for requesting the PD dataset.  I tried to get in contact with Adrien and Pavel, but I did not receive a response. Could you provide a email for that？

**Comment by pvtokmakov** [comment]
Hi Raymond. Sorry for the confusion. Not sure what happened with the emails, but the data is now released under this link:  https://tri-ml-public.s3.amazonaws.com/datasets/pd_release.tar.gz
